"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#9A348E)\
$os\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
$git_state\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$custom\
$nim\
$rust\
$scala\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
[](fg:#33658A bg:#86BBD8)\
$cmd_duration\
[ ]( fg:#86BBD8)\
$character\
"""

# [ ](fg:#06969A bg:#06969A)\

# Disable the blank line at the start of the prompt
add_newline = false

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10


[cmd_duration]
style = "bg:#86BBD8"
show_milliseconds = true
min_time = 100
show_notifications = true
min_time_to_notify = 50_000
format = '[  $duration ]($style)'

[character]
success_symbol = '✅ '
error_symbol = '❌ '
format = '[$symbol]($style)'

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = true

[os.symbols]
Macos = " "

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = false # Disabled by default
format = '[$symbol]($style)'

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = " "
home_symbol = "~"
# truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
disabled = true
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
disabled = true
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[elixir]
disabled = true
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
disabled = true
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_state]
style = "bg:#FCA17D"
merge = ""
format = '[\($state( $progress_current of $progress_total)\)]($style)'


[git_status]
style = "bg:#FCA17D"
ahead = '⇡${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = '⚑${count}'
format = '[$stashed $ahead_behind $state]($style)'

[golang]
disabled = true
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
disabled = true
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
disabled = true
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
disabled = true
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
disabled = true
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "󰎙 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[custom.fnm_nodejs]
command = "fnm current"
when = "true"
symbol = "󰎙 "
style = "bg:#86BBD8"
format = '[ $symbol ($output) ]($style)'
# format = " $symbol($output) "

[nim]
disabled = true
symbol = "󰆥 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
disabled = true
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
disabled = true
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%I:%M %p" # Hour:Minute AM/PM Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'
