"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#9A348E)\
$os\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
$git_state\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$custom\
$nim\
$rust\
$scala\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
$shell\
[](fg:#33658A bg:#86BBD8)\
$cmd_duration\
[ ]( fg:#86BBD8)\
$character\
"""
# [ ](fg:#06969A bg:#06969A)\

### Overwrite default time out from 500ms
command_timeout = 1000

# Disable the blank line at the start of the prompt
add_newline = true

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[cmd_duration]
format = '[  $duration ]($style)'
min_time = 10
min_time_to_notify = 50_000
show_milliseconds = true
show_notifications = true
style = "bg:#86BBD8 fg:#1f2937"

[character]
error_symbol = '❌ '
format = '[$symbol]($style) '
success_symbol = '✅ '

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
disabled = true
format = '[$user ]($style)'
show_always = true
style_root = "bg:#9A348E"
style_user = "bg:#9A348E"

[os.symbols]
Macos = " "

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
disabled = false # Disabled by default
format = '[$symbol]($style)' 
style = "bg:#9A348E" 

[directory]
format = "[ $path ]($style)"
home_symbol = "~"
style = "bg:#DA627D fg:#1f2937"
truncation_length = 2
truncation_symbol = " "
# truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
disabled = true
format = '[ $symbol ($version) ]($style)'
style = "bg:#86BBD8"
symbol = " "

[docker_context]
disabled = true
format = '[ $symbol $context ]($style)'
style = "bg:#06969A"
symbol = " "

[elixir]
disabled = true
format = '[ $symbol ($version) ]($style)'
style = "bg:#86BBD8"
symbol = " "

[elm]
disabled = true
format = '[ $symbol ($version) ]($style)'
style = "bg:#86BBD8"
symbol = " "

[git_branch]
format = '[ $symbol $branch ]($style)'
style = "bg:#FCA17D fg:#1f2937"
symbol = ""

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style)'
merge = ""
style = "bg:#FCA17D fg:#1f2937"

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'
format = '[$stashed $ahead_behind $state]($style)'
stashed = '⚑${count}'
style = "bg:#FCA17D fg:#1f2937"

[golang]
disabled = true
format = '[ $symbol ($version) ]($style)'
style = "bg:#86BBD8"
symbol = " "

[gradle]
disabled = true
format = '[ $symbol ($version) ]($style)'
style = "bg:#86BBD8"

[haskell]
disabled = true
format = '[ $symbol ($version) ]($style)'
style = "bg:#86BBD8"
symbol = " "

[java]
disabled = true
format = '[ $symbol ($version) ]($style)'
style = "bg:#86BBD8"
symbol = " "

[julia]
disabled = true
format = '[ $symbol ($version) ]($style)'
style = "bg:#86BBD8"
symbol = " "

[nodejs]
format = '[ $symbol ($version) ]($style)'
style = "bg:#86BBD8 fg:#1f2937"
symbol = "󰎙 "

[custom.fnm_nodejs]
command = "fnm current"
format = '[ $symbol ($output) ]($style)'
style = "bg:#86BBD8 fg:#1f2937"
symbol = "󰎙 "
when = "true"
# format = " $symbol($output) "

[nim]
disabled = true
format = '[ $symbol ($version) ]($style)'
style = "bg:#86BBD8"
symbol = "󰆥 "

[rust]
disabled = true
format = '[ $symbol ($version) ]($style)'
style = "bg:#86BBD8"
symbol = ""

[scala]
disabled = true
format = '[ $symbol ($version) ]($style)'
style = "bg:#86BBD8"
symbol = " "

[time]
disabled = false 
format = '[ ♥ $time ]($style)' 
style = "bg:#33658A fg:#FFFFFF" 
time_format = "%I:%M %p" # Hour:Minute AM/PM Format
